### ISSUE TITLE
Add a view for other nodes on the network?

### ISSUE THREAD

**Issue by increddibelly** [hassio-addons/addon-foldingathome#1]
# Feature request:
I have an exisiting FAH installation that I'd like to monitor through homeassistant. I don't want my homeassistant sytem to fold at home.
Please make a separate addon, a lovelace card, so I can view my other installation(s)?

**Comment by kineticscreen** [comment]
+1 for this. Raspberry Pi would be rubbish even if it were compatible, but would be great to have some data from my PC that is grinding out folds!

**Comment by frenck** [comment]
> I have an exisiting FAH installation that I'd like to monitor through homeassistant.

That is called an integration, not an add-on.

Feature requests for Home Assistant and Home Assistant integration go here: 

<https://community.home-assistant.io/c/feature-requests/13>
