### ISSUE TITLE
Add HTTPS Configuration

### ISSUE THREAD

**Issue by pattyland** [hassio-addons/addon-foldingathome#2]
When I'm using Home Assistant with HTTPS enabled and click on "OPEN WEB UI" Chrome redirects me to http**s**://hassio:7396/. The only way to access the web ui is a left click and selecting "Open in private window".
I think this behaviour of Chrome is well meant, it just disturbs in this case very much. An accessibility over HTTPS is of course always a good idea I think.

**Comment by frenck** [comment]
I cannot reproduce this issue, not on Chrome, Brave or Vivaldi (which are all Chrome-based).

Furthermore, the URL is correct in the configuration: <https://github.com/hassio-addons/addon-foldingathome/blob/master/foldingathome/config.json#L7>

As far as the add-on is concerned, the correct link/URL is passed.

**Comment by pattyland** [comment]
After further research this is caused via HSTS, which is enabled by default in the nginx addon. Workaround: Disable HSTS in the addon and follow this instructions: https://stackoverflow.com/a/28586593

I still think HTTPS for this addon would still be great. Especially Chrome will soon show more and more warnings and already prohibits many things on HTTP pages.
