### ISSUE TITLE
any chanse for https support?

### ISSUE THREAD

**Issue by askusbloodfist** [hassio-addons/addon-foldingathome#4]
any chanse for https support?

**Comment by frenck** [comment]
I was not planning on adding it to this add-on.

If you need such a thing, I recommend using a reverse proxy.

**Comment by askusbloodfist** [comment]
but im talking about supporting certs already in place.

like other addons do with 

ssl: true
certfile: fullchain.pem
keyfile: privkey.pem

**Comment by askusbloodfist** [comment]
Seems mor ethat its about that it wont go over to name. it just sticks with the internal ip.
