### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by jb123567** [hassio-addons/addon-foldingathome#44]
My Folding at Home is working perfectly with the CPU but is unable to utilise the onboard graphics an intel 530. The add on recognises it's presence, but can't seem to use it, is this an issue or by design?

**Comment by frenck** [comment]
This is a platform limitation: we won't be able to provide GPU support via add-ons.

**Comment by jb123567** [comment]
> This is a platform limitation: we won't be able to provide GPU support via add-ons.

Thought that would be the case, thanks for confirming!
