### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by tamet83** [hassio-addons/addon-foldingathome#50]
Hi, I noticed that lately the addon uses half of my VM CPU even if it is set as light.

<img width="1014" alt="Screenshot 2022-11-18 alle 03 17 40" src="https://user-images.githubusercontent.com/7949570/202601520-cebe11c2-628b-4321-b5fa-92b203a61145.png">

<img width="660" alt="Screenshot 2022-11-18 alle 03 18 12" src="https://user-images.githubusercontent.com/7949570/202601625-d2e1e0e9-a9b7-4675-8a86-2b2cf7c45a28.png">

This causes my NUC i3 have constantly a high fan speed and it's very noisy.
I'd like so much to contribute the research but I've already replaced one fan because the previous got broken.

Is this CPU consumption normal even in light mode?

Thanks

**Comment by frenck** [comment]
> Hi, I noticed that lately the addon uses half of my VM CPU even if it is set as light.

Yeah... that is its purpose... It takes up all remaining CPU and uses it for calculations for research.

> Is this CPU consumption normal even in light mode?

Yes, it is just a lower priority. 

../Frenck
