### ISSUE TITLE
ARM64/AARCH64 Support needed

### ISSUE THREAD

**Issue by Intecpsp** [hassio-addons/addon-foldingathome#55]
# Problem/Motivation

> I am running HA in a VM on my M1 Max Mac and am unable to run this add-on

## Expected behavior

> This add-on runs in the HA VM on systems that can support it

## Actual behavior

> Blocked due to not being supported

## Steps to reproduce

> Search add-on in store

## Proposed changes

> Add support for AARCH64

In #7, #37, and #38 you mentioned not supporting this for Raspberry Pis. But since I am running this on a Mac, there shouldn't be any reason not to support it.

**Comment by frenck** [comment]
> But since I am running this on a Mac

That is cool, but that is not the standard use case and therefore not a consideration for me.

> there shouldn't be any reason not to support it.

That is up to me to decide. Supporting something does not just entail: "Installable" (which you seem to refer to). Supporting also means triaging issues, shipping updates, debugging, testing and things like that. The fact is, people, installing it on e.g., Pis are likely to run into issues running things like these. I'm not willing to carry that support burden.

../Frenck
