### ISSUE TITLE
How do I know what name I am in the Team 247478?

### ISSUE THREAD

**Issue by thisisbenwoo** [hassio-addons/addon-foldingathome#6]
# Problem/Motivation

> I can't figure out what Name I'm listed under (or if I'm even listed at all) as a member of Home Assistant (Team 247478)

**Comment by frenck** [comment]
By default it will be Anonymous, unless you set a name by clicking on Anonymous.

**Comment by thisisbenwoo** [comment]
Thank Franck.
Do you think it is worthwhile to document the FAHClient --configure
procedure? Also, document getting a passkey?


*Ben Woo*
(212) 724-1188
*this*is*ben*woo*@gmail.com <http://gmail.com/>*

**Comment by frenck** [comment]
I don't think I will maintain a duplicate piece of documentation.

**Comment by thisisbenwoo** [comment]
Fair enough.. just a suggestion. Thank you for all you do for the project.


*Ben Woo*
(212) 724-1188
*this*is*ben*woo*@gmail.com <http://gmail.com/>*
