### ISSUE TITLE
ARM Support for Folding@home - RPi support?

### ISSUE THREAD

**Issue by jperquin** [hassio-addons/addon-foldingathome#7]
# Problem/Motivation

> Understand that ARM support was added a few weeks back to Folding@home.

## Expected behavior

> Does this mean we can expect an RPi compatible add-on for HA soon?

**Comment by ulf78** [comment]
https://foldingathome.org/2020/11/24/new-client-with-arm-support/ 

Would be great if someone could pick this up :-)

**Comment by frenck** [comment]
There is really no reason to add that, it will cause issues and the processing power is to low for the effort.

I'm not taking the effort to add support for this.
