### ISSUE TITLE
cannot instal on raspberry pi 5

### ISSUE THREAD

**Issue by pacslim** [hassio-addons/addon-foldingathome#76]
# Problem/Motivation

> (Why the issue was filed)
cannot instal on raspberry pi 5
## Expected behavior
should work 
> (What you expected to happen)
fix
## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Share your system information.
